### ISSUE TITLE
全画面管理

### ISSUE THREAD

**Issue by dninomiya** [camp-team/healthy_management#48]
## 画面一覧

- [x] welcome画面 #126
- [x] トップ画面 #49 
- [x] daily-detail画面 #46 
- [x] body-management画面 #39  
- [x] editor-body #133
- [x] editor-breakfast  #56 
- [x] my-menu #57 
- [x] menu – recipe-detail #58 
- [x] menu – recipe-create #59 
- [x] menu – recipe-update #60  
- [x] menu – set-create #62  
- [x] menu – set-detail  #61 
- [x] menu – set-update #63 
- [x] プロフィール画面 #16 
- [x] account #64 
- [x] terms #65 
- [x] legal #66 
- [x] usage #128 
- [x] 404画面 #90
## その他
- [x] チャート #11 
- [x] GitHub Actions #87
- [x] Stripe #45 
- [x] バッファ #100
